version: '3'


networks:
  default:
    driver: bridge


services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8089:8080"
    networks:
      - default
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    build:
      context: ../
      dockerfile: ./docker/mysql/Dockerfile
    networks:
      - default
    ports:
      - "3366:3306"
    volumes:
      - "../database:/var/lib/mysql"
