version: '3'


networks:
  default:
    driver: bridge


services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8089:8080"
    networks:
      - default
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    networks:
      - default
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_DATABASE: dd
    volumes:
      - "../database:/var/lib/mysql"
